name: CI
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: read

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Setup Node.js
              id: setup-node
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0

            - name: Forbid non-exact version ranges in package.json
              run: '! grep -qE "\"\\s*:\\s*\"[\^~]" package.json'

            - name: Install dependencies
              run: npm ci

    build-package:
        needs: build-and-test
        permissions:
            contents: read
            packages: write
            id-token: write
            attestations: write
            security-events: write
        uses: the-most-secure-supply-chain-ever-maaan/workflows/.github/workflows/build-package.yml@b83973aaf17faeceb9d58ecd39b453cf300663d3 
